### ISSUE TITLE
Add Maintainers?

### ISSUE THREAD

**Issue by nishanttotla** [nishanttotla/DockerStaticSite#3]
This repo is seeing some activity beyond what I'd anticipated.

@Oleg-Anuchin given you have been actively responding, do you wish to become a maintainer?

**Comment by apsyleg** [comment]
Hi @nishanttotla!
I can help you to maintain this project if I have some time.
At least I can help other people with issues :)

**Comment by nishanttotla** [comment]
Hi @Oleg-Anuchin sorry for the late response, I've been traveling on and off. If you're still interested, please let me know!
