### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by wildeyes** [nishanttotla/DockerStaticSite#4]
Gives out error:
> Status: Downloaded newer image for nginx:alpine
>  ---> 994032453556
> COPY failed: stat /var/lib/docker/tmp/docker-builder465167592/default.conf: no such file or directory
> Step 2/5 : COPY default.conf /etc/nginx/conf.d/default.conf
> Error! Build failed

**Comment by nishanttotla** [comment]
@wildeyes I think some command line options may have changed. I'll take a look.

**Comment by apsyleg** [comment]
Hi @wildeyes 
Have you resolved this issue?

**Comment by wildeyes** [comment]
No

**Comment by apsyleg** [comment]
> No

@wildeyes 
Thank you for your feedback.
Could you provide additional information?
- Commands you are entering
- Docker version
- Operation system name and version

It will help us to reproduce and fix the issue.

**Comment by apsyleg** [comment]
Hi @wildeyes 
Are you still interested in resolving this issue?

**Comment by wildeyes** [comment]
Would love to, but don't have time to work it out ATM :) I guess you can close this.
